### ISSUE TITLE
Error when upgrade OpenZeppelinTransparentProxy :(( 

### ISSUE THREAD

**Issue by hoangtrung99** [wighawag/tutorial-hardhat-deploy#8]
My deploy script
```js
// 005_deploy_pack.ts
import { DeployFunction } from "hardhat-deploy/dist/types";
import { NamedAccounts } from "hardhat.config";
import { HardhatRuntimeEnvironment } from "hardhat/types";
import { getContracts } from "../utils";

const deployFn: DeployFunction = async (hre: HardhatRuntimeEnvironment) => {
  const { deployments, getNamedAccounts } = hre;
  const { deploy } = deployments;
  const { deployer } = (await getNamedAccounts()) as NamedAccounts;

  const { base, setting, nft } = await getContracts(false);

  const args = [base?.address, base?.address, setting?.address, nft?.address];

  try {
    await deploy("CardPack", {
      from: deployer,
      log: true,
      proxy: {
        proxyContract: "OpenZeppelinTransparentProxy",
        execute: {
          methodName: "initialize",
          args,
        },
      },
    });
  } catch (error) {
    console.log(error);
  }
};

export default deployFn;

deployFn.tags = ["pack"];

```

I did it successfully the first time I deploy, but when I wanted to upgrade, I ran that script for the second time.
I'm pretty sure the args passed in is correct.
```bash
npx hardhat --network ropsten deploy --tags pack
```
and get this error.
```bash
reusing "DefaultProxyAdmin" at 0x789C142E0ad410495087ac68d430e5Ca43618c13
deploying "CardPack_Implementation" (tx: 0x37f505b4faaa437caf948941e8f28500261bd5c85fc7c227d3ffa3dafb163337)...: deployed at 0x980Ba4459b90AD9602303f9aFE5aBD4429ae4631 with 1429861 gas
Error: cannot estimate gas; transaction may fail or may require manual gas limit (error={"name":"ProviderError","code":-32000,"_isProviderError":true}, method="estimateGas", transaction={"from":"0x54A96b7E99a9F8A3bC105206B851F277De8D64Fc","to":"0x789C142E0ad410495087ac68d430e5Ca43618c13","data":"0x9623609d0000000000000000000000004a2d8b430de79802c980c5718f03bed96f6d7b41000000000000000000000000980ba4459b90ad9602303f9afe5abd4429ae463100000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000084f8c8765e0000000000000000000000005363888510cfa5241c865f4463408079147505c90000000000000000000000005363888510cfa5241c865f4463408079147505c900000000000000000000000076995ab1384476adbcedd422af38de61b77f47bc0000000000000000000000003d3cac7d0f300c4f8c28231f57e111f5a6b1baf500000000000000000000000000000000000000000000000000000000","accessList":null}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.4.5)
    at Logger.makeError (/Users/hoangtrung/solashi/gacha-contract-2/node_modules/@ethersproject/logger/src.ts/index.ts:225:28)
    at Logger.throwError (/Users/hoangtrung/solashi/gacha-contract-2/node_modules/@ethersproject/logger/src.ts/index.ts:237:20)
    at checkError (/Users/hoangtrung/solashi/gacha-contract-2/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:80:16)
    at Web3Provider.<anonymous> (/Users/hoangtrung/solashi/gacha-contract-2/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:555:20)
    at step (/Users/hoangtrung/solashi/gacha-contract-2/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
    at Object.throw (/Users/hoangtrung/solashi/gacha-contract-2/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
    at rejected (/Users/hoangtrung/solashi/gacha-contract-2/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: 'cannot estimate gas; transaction may fail or may require manual gas limit',
  code: 'UNPREDICTABLE_GAS_LIMIT',
  error: ProviderError: execution reverted
      at HttpProvider.request (/Users/hoangtrung/solashi/gacha-contract-2/node_modules/hardhat/src/internal/core/providers/http.ts:49:19)
      at LocalAccountsProvider.request (/Users/hoangtrung/solashi/gacha-contract-2/node_modules/hardhat/src/internal/core/providers/accounts.ts:168:34)
      at processTicksAndRejections (node:internal/process/task_queues:96:5),
  method: 'estimateGas',
  transaction: {
    from: '0x54A96b7E99a9F8A3bC105206B851F277De8D64Fc',
    to: '0x789C142E0ad410495087ac68d430e5Ca43618c13',
    data: '0x9623609d0000000000000000000000004a2d8b430de79802c980c5718f03bed96f6d7b41000000000000000000000000980ba4459b90ad9602303f9afe5abd4429ae463100000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000084f8c8765e0000000000000000000000005363888510cfa5241c865f4463408079147505c90000000000000000000000005363888510cfa5241c865f4463408079147505c900000000000000000000000076995ab1384476adbcedd422af38de61b77f47bc0000000000000000000000003d3cac7d0f300c4f8c28231f57e111f5a6b1baf500000000000000000000000000000000000000000000000000000000',
    accessList: null
  }
}
```
I tried setting GasLimit manually and then got this error
```bash
reusing "DefaultProxyAdmin" at 0x789C142E0ad410495087ac68d430e5Ca43618c13
deploying "CardPack_Implementation" (tx: 0xbe8c77c99a887f074a3654dfb4b8281030e74c33f345617fedc0b355cb09cb21)...: deployed at 0x9A253dD367E8861ca21C97FF70A0B0f7b20E57ef with 1429861 gas
executing DefaultProxyAdmin.upgradeAndCall (tx: 0xeb4b46e5654245e823c40cee39db09bdfcdcc8dc9f9138fa6c2477d0e27b2023) ...Error: transaction failed (transactionHash="0xeb4b46e5654245e823c40cee39db09bdfcdcc8dc9f9138fa6c2477d0e27b2023", transaction={"hash":"0xeb4b46e5654245e823c40cee39db09bdfcdcc8dc9f9138fa6c2477d0e27b2023","type":0,"accessList":null,"blockHash":null,"blockNumber":null,"transactionIndex":null,"confirmations":0,"from":"0x54A96b7E99a9F8A3bC105206B851F277De8D64Fc","gasPrice":{"type":"BigNumber","hex":"0x09502f9000"},"gasLimit":{"type":"BigNumber","hex":"0x4c4b40"},"to":"0x789C142E0ad410495087ac68d430e5Ca43618c13","value":{"type":"BigNumber","hex":"0x00"},"nonce":2108,"data":"0x9623609d0000000000000000000000004a2d8b430de79802c980c5718f03bed96f6d7b410000000000000000000000009a253dd367e8861ca21c97ff70a0b0f7b20e57ef00000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000084f8c8765e0000000000000000000000005363888510cfa5241c865f4463408079147505c90000000000000000000000005363888510cfa5241c865f4463408079147505c900000000000000000000000076995ab1384476adbcedd422af38de61b77f47bc0000000000000000000000003d3cac7d0f300c4f8c28231f57e111f5a6b1baf500000000000000000000000000000000000000000000000000000000","r":"0x6d15b64643a12281d5985498cfad3ccd3fefcf2e4c86d95adc8185372f4b9737","s":"0x5913e0759ffb605893f9fda97808f5bdaa774870c2e5fb68d0a373e64dd7c186","v":42,"creates":null,"chainId":3}, receipt={"to":"0x789C142E0ad410495087ac68d430e5Ca43618c13","from":"0x54A96b7E99a9F8A3bC105206B851F277De8D64Fc","contractAddress":null,"transactionIndex":1,"gasUsed":{"type":"BigNumber","hex":"0xaf88"},"logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","blockHash":"0xdc9137206a080fde99a80c1dcf9ba0606eb1fa9cdf398d2187892f412b925d01","transactionHash":"0xeb4b46e5654245e823c40cee39db09bdfcdcc8dc9f9138fa6c2477d0e27b2023","logs":[],"blockNumber":11259196,"confirmations":1,"cumulativeGasUsed":{"type":"BigNumber","hex":"0x0114ca"},"effectiveGasPrice":{"type":"BigNumber","hex":"0x09502f9000"},"status":0,"type":0,"byzantium":true}, code=CALL_EXCEPTION, version=providers/5.4.5)
    at Logger.makeError (/Users/hoangtrung/solashi/gacha-contract-2/node_modules/@ethersproject/logger/src.ts/index.ts:225:28)
    at Logger.throwError (/Users/hoangtrung/solashi/gacha-contract-2/node_modules/@ethersproject/logger/src.ts/index.ts:237:20)
    at Web3Provider.<anonymous> (/Users/hoangtrung/solashi/gacha-contract-2/node_modules/@ethersproject/providers/src.ts/base-provider.ts:1198:24)
    at step (/Users/hoangtrung/solashi/gacha-contract-2/node_modules/@ethersproject/providers/lib/base-provider.js:48:23)
    at Object.next (/Users/hoangtrung/solashi/gacha-contract-2/node_modules/@ethersproject/providers/lib/base-provider.js:29:53)
    at fulfilled (/Users/hoangtrung/solashi/gacha-contract-2/node_modules/@ethersproject/providers/lib/base-provider.js:20:58) {
  reason: 'transaction failed',
  code: 'CALL_EXCEPTION',
  transactionHash: '0xeb4b46e5654245e823c40cee39db09bdfcdcc8dc9f9138fa6c2477d0e27b2023',
  transaction: {
    hash: '0xeb4b46e5654245e823c40cee39db09bdfcdcc8dc9f9138fa6c2477d0e27b2023',
    type: 0,
    accessList: null,
    blockHash: null,
    blockNumber: null,
    transactionIndex: null,
    confirmations: 0,
    from: '0x54A96b7E99a9F8A3bC105206B851F277De8D64Fc',
    gasPrice: BigNumber { _hex: '0x09502f9000', _isBigNumber: true },
    gasLimit: BigNumber { _hex: '0x4c4b40', _isBigNumber: true },
    to: '0x789C142E0ad410495087ac68d430e5Ca43618c13',
    value: BigNumber { _hex: '0x00', _isBigNumber: true },
    nonce: 2108,
    data: '0x9623609d0000000000000000000000004a2d8b430de79802c980c5718f03bed96f6d7b410000000000000000000000009a253dd367e8861ca21c97ff70a0b0f7b20e57ef00000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000084f8c8765e0000000000000000000000005363888510cfa5241c865f4463408079147505c90000000000000000000000005363888510cfa5241c865f4463408079147505c900000000000000000000000076995ab1384476adbcedd422af38de61b77f47bc0000000000000000000000003d3cac7d0f300c4f8c28231f57e111f5a6b1baf500000000000000000000000000000000000000000000000000000000',
    r: '0x6d15b64643a12281d5985498cfad3ccd3fefcf2e4c86d95adc8185372f4b9737',
    s: '0x5913e0759ffb605893f9fda97808f5bdaa774870c2e5fb68d0a373e64dd7c186',
    v: 42,
    creates: null,
    chainId: 3,
    wait: [AsyncFunction (anonymous)]
  },
  receipt: {
    to: '0x789C142E0ad410495087ac68d430e5Ca43618c13',
    from: '0x54A96b7E99a9F8A3bC105206B851F277De8D64Fc',
    contractAddress: null,
    transactionIndex: 1,
    gasUsed: BigNumber { _hex: '0xaf88', _isBigNumber: true },
    logsBloom: '0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
    blockHash: '0xdc9137206a080fde99a80c1dcf9ba0606eb1fa9cdf398d2187892f412b925d01',
    transactionHash: '0xeb4b46e5654245e823c40cee39db09bdfcdcc8dc9f9138fa6c2477d0e27b2023',
    logs: [],
    blockNumber: 11259196,
    confirmations: 1,
    cumulativeGasUsed: BigNumber { _hex: '0x0114ca', _isBigNumber: true },
    effectiveGasPrice: BigNumber { _hex: '0x09502f9000', _isBigNumber: true },
    status: 0,
    type: 0,
    byzantium: true
  }
}
```

Please help me, I decided to use this great plugin but it is giving me real problem :(

**Comment by wighawag** [comment]
I guess your initialize function is not meant to be executed twice

the way you call deploy, witrh `execute` means initialise is going to be called on every upgrade.

try this instead:
```js
await deploy("CardPack", {
      from: deployer,
      log: true,
      proxy: {
        proxyContract: "OpenZeppelinTransparentProxy",
        execute: {
          init: {
            methodName: "initialize",
            args,
          },
        }
      },
    });
 ```

**Comment by hoangtrung99** [comment]
@wighawag 
Wow, glad you replied so soon, I'm coming home from work, I'll try it again as soon as I get home.
Thank you very much.

**Comment by hoangtrung99** [comment]
Great, it worked as expected.
Thank you very much @wighawag :100:
